#!/usr/bin/env perl

$location='/home/people/mutation_testing/cleaned_test_suites/Time/evosuite/2/Time-1f-evosuite.2.tar.bz2';

$file = GetFile($location);


#$file = '/home/people/12309511/all_tests/Time/evosuite/2/1f/tests.txt';

#print $file;

open $info, $file or die "Could not open $file: $!";

$test_class = '';

while( my $line = <$info>) {
	if (index($line, "Test") != -1) {
		#print $line;
		#print " Class\n";
		$test_class=join('', split(/\n/, $line));
	} elsif (index($line, "test") != -1) {
		#print $line;
		#print " Method\n";
		$test_method=join('', split(/\n/, $line));
		$test_method =~ s/[()]//g;
	
		$test=$test_class . "::" . $test_method;
		print $test;
		print "\n";
		#print "${test_class}::${test_method}";
	}
	


	#print $line;
}

close $info;

sub GetFile {
	$suite = $_[0];
	print $suite . "\n";

	#Parse location to get test file
	@split = split('/', $suite);
	
	$project = $split[5];
	$gen = $split[6];
	$seed = $split[7];
	$tar_file = $split[8];
	
	@tar_split = split('-', $tar_file);
	
	$version = $tar_split[1];	

	print $project . "\n" . $gen . "\n" . $seed . "\n" . $version . "\n";

	$file_location = "/home/people/12309511/all_tests/" . $project . "/" . $gen . "/" . $seed . "/" . $version ."/tests.txt";
	print "LOCATION: " . $file_location;

	return $file_location;
}
