#!/usr/bin/env perl

my $TEST_METHODS_FILE = '/home/people/12309511/dev_all_test_methods/JxPath/13f/test_methods.txt';
open my $info, $TEST_METHODS_FILE or die "Could not open $TEST_METHODS_FILE: $!";

my $test_class = '';

while(my $line = <$info>) {
        if (index($line, "Test") != -1) {
            $test_class=join('', split(/\n/, $line));
        } elsif (index($line, "test") != -1) {
            my $test_method=join('', split(/\n/, $line));
            $test_method =~ s/[()]//g;

            my $test = $test_class . "::" . $test_method;
            print $test;
            print "\n";
	}
}
